# Generated by Django 5.0.6 on 2024-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionequipo',
            name='equipo',
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='equipos',
            field=models.ManyToManyField(to='equipment_inventory.inventarioequipo'),
        ),
    ]
