# Generated by Django 5.0.6 on 2024-06-21 16:04

from django.db import migrations, models

from equipment_inventory.models import Empleado, InventarioEquipo


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0002_remove_asignacionequipo_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioequipo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='nombre_del_equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='modelo',
            field=models.CharField(choices=[('ThinkCentre', 'ThinkCentre'), ('HP Prodesk 600 G6', 'HP Prodesk 600 G6'), ('Probook 440 G7', 'Probook 440 G7'), ('ThinkPad', 'ThinkPad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='ubicacion',
            field=models.CharField(choices=[('Departamento Compras', 'Departamento Compras'), ('Departamento Almacenes y Trafico', 'Departamento Almacenes y Trafico'), ('Departamento Proveedores', 'Departamento Proveedores'), ('Soporte Tecnico', 'Soporte Tecnico'), ('Auxiliaria General', 'Auxiliaria General')], max_length=100),
        ),
    ]

