# Generated by Django 5.0.6 on 2024-06-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0003_remove_inventarioequipo_usuario_inventarioequipo_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionequipo',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='asignacionequipo',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='inventarioequipo',
            name='nombre_del_equipo',
        ),
        migrations.RemoveField(
            model_name='inventarioequipo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment_inventory.inventarioequipo'),
        ),
        migrations.AddField(
            model_name='inventarioequipo',
            name='nombre_equipo',
            field=models.CharField(default='Equipo Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='estado',
            field=models.CharField(default='nuevo', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
