# Generated by Django 5.0.6 on 2024-06-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0004_remove_asignacionequipo_equipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_inventory.inventarioequipo'),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='fecha_asignacion',
            field=models.DateField(),
        ),
    ]
